In [21]:
import pandas as pd

**Note:** This is a data cleaning and preprocessing exercise. Ensure that all data preprocessing and transformations are continually updated in the data frame that will be saved towards the end of the exercise.

# Task 1
## Inspect the data
- Load the data
- Display the first 5 rows
- Display 5 random rows
- Check the number of rows and columns
- Inspect the data types of all features

In [22]:
df = pd.read_csv('/content/nykaa_data_preprocessing.csv')

print('First 5 rows:')
display(df.head())

print('\n5 random rows:')
display(df.sample(5))

print('\nNumber of rows and columns:')
print(df.shape)

print('\nData types of all features:')
display(df.info())

First 5 rows:

,Product Id,Product Brand Code,Product Category,Product Brand,Product Name,Product Price,Product Url,Productdescription,Product Image Url,Product Tags,Product Contents,Product Rating,Product Reviews Count,Expected Category Count,Expected Brand Count
0,f54658c5d511195b6621a640fb743b1b,BH5931,brand > l'oreal paris,L'OREAL PARIS,L'Oreal Paris Glow Mon Amour Highlighting Drop...,454,https://www.nykaa.com/c/p/565974?skuId=565973,It's time to skip the snooze button and get up...,https://images-static.nykaa.com/media/catalog/...,L'Oreal Paris Glow Mon Amour Highlighting Drop...,"G927637, Cyclopentasiloxane, Dimethicone, Isod...",4.3,147,431,431
1,424755c11c78b2b24ff13c675baf5d19,BZ1000,health & wellness > good for you > super food,TRUE ELEMENTS,True Elements Sunflower Raw Seeds,175,https://www.nykaa.com/c/p/370883?skuId=370881,Sunflower has always been admired for its beau...,https://images-static.nykaa.com/media/catalog/...,"True Elements Sunflower Raw Seeds, Wellness, S...",Raw Sunflower Seeds,5.0,0,389,149
2,e22a7ea6c594e3e52a4dbe1eb04fd7a3,BH5825,brand > nivea,NIVEA,NIVEA Body Lotion Oil in Lotion Rose & Argan O...,260,https://www.nykaa.com/c/p/353370?skuId=353368,Indulge in the goodness of natural oils in a f...,https://images-static.nykaa.com/media/catalog/...,"Nivea Oil In Lotion Rose & Argan Oil, Skin, Bo...","Aqua, Glycerin, Dicaprylyl Ether, Alcohol Dena...",4.5,1220,160,160
3,20532c740b21fcecfeecebc2ad1c5a8d,BZ1000,natural > skin > face wash,LOTUS HERBALS,Lotus Herbals Whiteglow Activated Charcoal Bri...,140,https://www.nykaa.com/c/p/811670?skuId=811668,Lotus Herbals WhiteGlow Activated Charcoal Bri...,NaN,Lotus Herbals Whiteglow Activated Charcoal Bri...,Key Ingredients:Activated Charcoal (Coconut Sh...,4.2,8,922,274
4,3cef574c3a1f4f9c4a01ca889e46a5c9,BZ1000,makeup > face > concealer,SMASHBOX,Smashbox Color Correcting Stick - Look Less Ti...,2090,NaN,"These creamy, color-correcting sticks camoufla...",https://images-static.nykaa.com/media/catalog/...,Smashbox Color Correcting Stick - Look Less Ti...,"Formulated without parabens, sodium lauryl sul...",4.1,13,258,143

5 random rows:

,Product Id,Product Brand Code,Product Category,Product Brand,Product Name,Product Price,Product Url,Productdescription,Product Image Url,Product Tags,Product Contents,Product Rating,Product Reviews Count,Expected Category Count,Expected Brand Count
240,b65b0fecf6bc9116a509dcb399cb88b4,BZ1000,natural > trending searches > tea tree oil,VAADI HERBALS,Vaadi Herbals Dandruff Defense Lemon Shampoo W...,128,https://www.nykaa.com/c/p/76268?skuId=76218,Combat your hair problems with this expert rem...,https://images-static.nykaa.com/media/catalog/...,Vaadi Herbals Dandruff Defense Lemon Shampoo W...,"Lemon Extract, Tea Tree Extract , Hibiscus, Re...",4.3,4,564,0
215,f01f03b08350e6d7a6f1b21f3badee0f,BH7318,skin > moisturizers > bb & cc cream,CLINIQUE,Clinique Moisture Surge CC Cream Hydrating Col...,3850,https://www.nykaa.com/c/p/76683?skuId=76680,What it is: A colour correcting cream that pro...,https://images-static.nykaa.com/media/catalog/...,Clinique Moisture Surge CC Cream Hydrating Col...,"Water\\Aqua\\Eau , Ethylhexyl Methoxycinnamate...",3.7,19,0,0
137,c646fc3fe1072ba3f7c85acae94730f9,BZ1000,personal care > face > moisturizer,LOTUS HERBALS,Lotus Herbals Cocomoist Cocoa-Butter Moisturis...,295,https://www.nykaa.com/c/p/13526?skuId=13524,Lotus Herbal Cocomoist Cocoa-Butter Moisturisi...,https://images-static.nykaa.com/media/catalog/...,Lotus Herbals Cocomoist Cocoa-Butter Moisturis...,Cocoa Butter- Excellent Skin emollient(softeni...,4.6,81,1364,274
230,5a983b899dbe450ffbcc43af7e0149ee,BH6523,brand > himalaya,HIMALAYA,Himalaya Herbals Refreshing Cleansing Milk,84,https://www.nykaa.com/c/p/6022?skuId=3451,Himalaya's Refreshing Cleansing Milk contains ...,https://images-static.nykaa.com/media/catalog/...,"himalaya herbals refreshing cleansing milk, hi...","Citrus limon(Lemon, Nimbaka) Vitis vinifera(Gr...",4.3,1140,328,0
211,0419250ea105a0b2e77d86a625b26a4f,BZ1000,natural > shop by concern > pigmentation,NEEMLI NATURALS,Neemli Naturals Glycolic Acid & Hydrolysed Col...,675,https://www.nykaa.com/c/p/813048?skuId=813046,"Of all things that linger, scars and pits from...",https://images-static.nykaa.com/media/catalog/...,Neemli Naturals Glycolic Acid & Hydrolysed Col...,Key Ingredients:Glycolic Acid: A type of Alpha...,4.5,11,1546,0

Number of rows and columns:
(263, 15)

Data types of all features:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product Id               263 non-null    object
 1   Product Brand Code       263 non-null    object
 2   Product Category         263 non-null    object
 3   Product Brand            263 non-null    object
 4   Product Name             263 non-null    object
 5   Product Price            263 non-null    int64
 6   Product Url              244 non-null    object
 7   Productdescription       263 non-null    object
 8   Product Image Url        242 non-null    object
 9   Product Tags             263 non-null    object
 10  Product Contents         263 non-null    object
 11  Product Rating           248 non-null    float64
 12  Product Reviews Count    263 non-null    int64
 13  Expected Category Count  263 non-null    int64
 14  Expected Brand Count     263 non-null    int64
dtypes: float64(1), int64(4), object(10)
memory usage: 30.9+ KB

None

# Task 2
## Fix data types
- Ensure that all features are stored in the most suitable data type
- Convert the `'Product Price'` feature to `float64` data type

In [23]:
# Identify columns with non-suitable data types and convert them

# Convert 'Product Price' to float64
# First, clean the 'Product Price' column by removing non-numeric characters
# Assuming currency symbols like '₹' and commas ',' might be present
df['Product Price'] = df['Product Price'].astype(str).str.replace('₹', '', regex=False)
df['Product Price'] = df['Product Price'].astype(str).str.replace(',', '', regex=False)

# Convert to float64, coercing errors to NaN
df['Product Price'] = pd.to_numeric(df['Product Price'], errors='coerce')

# Display data types again to confirm changes
print('Updated data types after type conversion:')
display(df.info())

Updated data types after type conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product Id               263 non-null    object
 1   Product Brand Code       263 non-null    object
 2   Product Category         263 non-null    object
 3   Product Brand            263 non-null    object
 4   Product Name             263 non-null    object
 5   Product Price            263 non-null    int64
 6   Product Url              244 non-null    object
 7   Productdescription       263 non-null    object
 8   Product Image Url        242 non-null    object
 9   Product Tags             263 non-null    object
 10  Product Contents         263 non-null    object
 11  Product Rating           248 non-null    float64
 12  Product Reviews Count    263 non-null    int64
 13  Expected Category Count  263 non-null    int64
 14  Expected Brand Count     263 non-null    int64
dtypes: float64(1), int64(4), object(10)
memory usage: 30.9+ KB

None

# Task 3
## Handle missing values
- Identify columns with missing values
- Replace missing values in string columns with `'nodata'`
- Replace missing numeric values with median

In [24]:
# Identify columns with missing values
print('Missing values before handling:')
print(df.isnull().sum())

# Separate columns into numeric and string/object types
numeric_cols = df.select_dtypes(include=['number']).columns
string_cols = df.select_dtypes(include=['object']).columns

# Replace missing values in string columns with 'nodata'
for col in string_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna('nodata')

# Replace missing numeric values with the median
for col in numeric_cols:
    if df[col].isnull().any():
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

# Display missing values after handling to confirm
print('\nMissing values after handling:')
print(df.isnull().sum())

Missing values before handling:
Product Id                  0
Product Brand Code          0
Product Category            0
Product Brand               0
Product Name                0
Product Price               0
Product Url                19
Productdescription          0
Product Image Url          21
Product Tags                0
Product Contents            0
Product Rating             15
Product Reviews Count       0
Expected Category Count     0
Expected Brand Count        0
dtype: int64

Missing values after handling:
Product Id                 0
Product Brand Code         0
Product Category           0
Product Brand              0
Product Name               0
Product Price              0
Product Url                0
Productdescription         0
Product Image Url          0
Product Tags               0
Product Contents           0
Product Rating             0
Product Reviews Count      0
Expected Category Count    0
Expected Brand Count       0
dtype: int64

# Task 4
## Remove duplicate records
- Check whether duplicate rows exist
- Remove duplicate records
- Display how many rows were removed

In [25]:
# Check for duplicate rows
duplicate_rows_before = df.duplicated().sum()
print(f"Number of duplicate rows before removal: {duplicate_rows_before}")

# Remove duplicate records
df.drop_duplicates(inplace=True)

# Display how many rows were removed
duplicate_rows_after = df.duplicated().sum()
removed_rows = duplicate_rows_before - duplicate_rows_after
print(f"Number of duplicate rows after removal: {duplicate_rows_after}")
print(f"Number of rows removed: {removed_rows}")

Number of duplicate rows before removal: 11
Number of duplicate rows after removal: 0
Number of rows removed: 11

# Task 5
## Standardise column names
- Remove any leading and trailing whitespaces from column names
- Convert all column names to lowercase
- Replace spaces between words with underscores (`_`)
- Ensure there are no multiple consecutive underscores
- Remove any leading or trailing underscores
- Display the updated column names

In [26]:
# Standardise column names

# Get current column names
current_columns = df.columns

# Create a list to hold new column names
new_columns = []

for col in current_columns:
    # 1. Remove any leading and trailing whitespaces
    col = col.strip()
    # 2. Convert all column names to lowercase
    col = col.lower()
    # 3. Replace spaces between words with underscores
    col = col.replace(' ', '_')
    # 4. Ensure there are no multiple consecutive underscores
    col = '_'.join(filter(None, col.split('_')))
    # 5. Remove any leading or trailing underscores (after joining, filter(None) already handles multiple underscores reducing to single and removing leading/trailing if they result from empty strings after split)
    col = col.strip('_')
    new_columns.append(col)

# Assign the new column names back to the DataFrame
df.columns = new_columns

# Display the updated column names
print('Updated column names:')
print(df.columns)

Updated column names:
Index(['product_id', 'product_brand_code', 'product_category', 'product_brand',
       'product_name', 'product_price', 'product_url', 'productdescription',
       'product_image_url', 'product_tags', 'product_contents',
       'product_rating', 'product_reviews_count', 'expected_category_count',
       'expected_brand_count'],
      dtype='object')

# Task 6
## Engineer new features
- Create a column `'price_category'`:
    - `'low'` if product price is less than 500
    - `'medium'` if product price is between 500 and 2000 (both inclusive)
    - `'high'` if product price is greater than 2000
- Create a column `'has_reviews'`:
    - `'yes'` if the product has at least one review
    - `'no'` otherwise
- Obtain the mode of the `'price_category'` feature

In [27]:
# Create 'price_category' column
def get_price_category(price):
    if price < 500:
        return 'low'
    elif 500 <= price <= 2000:
        return 'medium'
    else:
        return 'high'

df['price_category'] = df['product_price'].apply(get_price_category)

# Create 'has_reviews' column
df['has_reviews'] = df['product_reviews_count'].apply(lambda x: 'yes' if x > 0 else 'no')

# Obtain the mode of the 'price_category' feature
price_category_mode = df['price_category'].mode()[0]

print(f"Mode of 'price_category': {price_category_mode}")
print("\nFirst 5 rows with new features:")
display(df[['product_price', 'price_category', 'product_reviews_count', 'has_reviews']].head())

Mode of 'price_category': low

First 5 rows with new features:

   product_price price_category  product_reviews_count has_reviews
0            454            low                    147         yes
1            175            low                      0          no
2            260            low                   1220         yes
3            140            low                      8         yes
4           2090           high                     13         yes

# Task 7
## Treat outliers
- Use the interquartile range (IQR) method to identify outliers in the `'product_price'` column
  - IQR = Q3 - Q1, UL = Q3 + 1.5 * IQR, LL = Q1 - 1.5 * IQR
- Find the number of outliers according to the IQR method and treat them by capping them to the UL or the LL accordingly

In [28]:
# Treat outliers in 'product_price' using IQR method

# Calculate Q1, Q3, and IQR for 'product_price'
Q1 = df['product_price'].quantile(0.25)
Q3 = df['product_price'].quantile(0.75)
IQR = Q3 - Q1

# Calculate Upper Limit (UL) and Lower Limit (LL)
UL = Q3 + 1.5 * IQR
LL = Q1 - 1.5 * IQR

print(f"Q1 for product_price: {Q1}")
print(f"Q3 for product_price: {Q3}")
print(f"IQR for product_price: {IQR}")
print(f"Upper Limit (UL) for product_price: {UL}")
print(f"Lower Limit (LL) for product_price: {LL}")

# Find the number of outliers
outliers = df[(df['product_price'] < LL) | (df['product_price'] > UL)]
num_outliers = len(outliers)
print(f"\nNumber of outliers in 'product_price': {num_outliers}")

# Treat outliers by capping them to UL or LL
df['product_price'] = df['product_price'].clip(lower=LL, upper=UL)

# Verify that outliers have been treated (optional, but good for checking)
num_outliers_after = len(df[(df['product_price'] < LL) | (df['product_price'] > UL)])
print(f"Number of outliers in 'product_price' after capping: {num_outliers_after}")

print("\nFirst 5 rows of 'product_price' after outlier treatment:")
display(df[['product_price']].head())

Q1 for product_price: 150.0
Q3 for product_price: 1113.25
IQR for product_price: 963.25
Upper Limit (UL) for product_price: 2558.125
Lower Limit (LL) for product_price: -1294.875

Number of outliers in 'product_price': 27
Number of outliers in 'product_price' after capping: 0

First 5 rows of 'product_price' after outlier treatment:

   product_price
0          454.0
1          175.0
2          260.0
3          140.0
4         2090.0

# Task 8
## Write cleaned dataset to disk

In [29]:
df.to_csv('nykaa_eda.csv', index=False)