Let's import the Pandas library

In [1]:
import pandas as pd

Let's create an empty Pandas DataFrame

In [2]:
df_empty = pd.DataFrame()
df_empty

Empty DataFrame
Columns: []
Index: []

In [3]:
type(df_empty)

pandas.core.frame.DataFrame

In [4]:
df_empty.dtypes

Series([], dtype: object)

In [5]:
df_empty.ndim

2

In [6]:
df_empty.shape

(0, 0)

In [7]:
df_empty.size

0

In [8]:
df_empty.index

RangeIndex(start=0, stop=0, step=1)

In [9]:
df_empty.columns

RangeIndex(start=0, stop=0, step=1)

In [10]:
df_empty.values

array([], shape=(0, 0), dtype=float64)

Let's create some DataFrames with values

In [11]:
# From a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Chandni', 'Dawood'],
    'Age': [25, 30, 18, 22],
    'City': ['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru']
}

df1 = pd.DataFrame(data = data)
df1

      Name  Age       City
0    Alice   25     Mumbai
1      Bob   30    Kolkata
2  Chandni   18      Delhi
3   Dawood   22  Bengaluru

In [12]:
df1.dtypes

Name    object
Age      int64
City    object
dtype: object

In [13]:
df1.ndim

2

In [14]:
df1.shape

(4, 3)

In [15]:
df1.size

12

In [16]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
df1.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [18]:
df1.values

array([['Alice', 25, 'Mumbai'],
       ['Bob', 30, 'Kolkata'],
       ['Chandni', 18, 'Delhi'],
       ['Dawood', 22, 'Bengaluru']], dtype=object)

In [19]:
# From Pandas Series
names = pd.Series(['Alice', 'Bob', 'Chandni', 'Dawood'])
ages = pd.Series([25, 30, 18, 22])
cities = pd.Series(['Mumbai', 'Kolkata', 'Delhi', 'Bengaluru'])

# Create DataFrame from Series
df2 = pd.DataFrame({'Name': names, 'Age': ages, 'City': cities})
df2

      Name  Age       City
0    Alice   25     Mumbai
1      Bob   30    Kolkata
2  Chandni   18      Delhi
3   Dawood   22  Bengaluru