In [1]:
# Numpy and Pandas

In [2]:
# Python is a slow programming - We can make it faster by integrating Python with C or C++
    # Numpy - C Programming

In [4]:
sales = [4543,2344,5433,1233]
profit = [433,212,433,212]

for i in range(0,len(sales)):
    print(profit[i]/sales[i])

0.09531146819282413
0.09044368600682594
0.0796981409902448
0.17193836171938362

In [5]:
# Python - Anaconda 
# Python - Google Colab 
# Python - Python website - Numpy will not be part of it - We have explicitly install numpy pip install numpy

In [6]:
# FAANG

In [7]:
#Installation 
!pip install numpy==2.4.6

Requirement already satisfied: numpy in c:\users\dell\anaconda3\lib\site-packages (2.1.3)

In [8]:
import numpy as np

In [9]:
np.__version__

'2.1.3'

**https://numpy.org/**

In [10]:
sales = [4543,2344,5433,1233]
sales_array = np.array(sales)
profit = [433,212,433,212]
profit_array = np.array(profit)

In [11]:
sales_array

array([4543, 2344, 5433, 1233])

In [12]:
profit_array

array([433, 212, 433, 212])

In [13]:
profit_array/sales_array

array([0.09531147, 0.09044369, 0.07969814, 0.17193836])

In [14]:
sales

[4543, 2344, 5433, 1233]

In [15]:
sales_array

array([4543, 2344, 5433, 1233])

In [34]:
list1=[True]

array1=np.array(list1)

In [35]:
array1

array([ True])

In [27]:
# String takes the priority
# String>Float>Int>Bool

In [25]:
sales

[4543, 2344, 5433, 1233]

In [37]:
sales_array.size

4

In [ ]:
#Attribute

In [42]:
sales_array

array([4543, 2344, 5433, 1233])

In [39]:
sales_array.ndim

1

In [40]:
sales_array.shape

(4,)

In [54]:
sales_array

array([4543, 2344, 5433, 1233])

In [45]:
sales_array*3

array([13629,  7032, 16299,  3699])

In [46]:
sales*3

[4543, 2344, 5433, 1233, 4543, 2344, 5433, 1233, 4543, 2344, 5433, 1233]

In [47]:
sales_us = [4533,1233,4433,1223]
sales_eu = [5433,2322,1222,4332]
sales_in = [6554,5645,6564,3344]

In [49]:
sales_matrix = np.array([sales_us,sales_eu,sales_in])

In [51]:
sales_matrix.shape

(3, 4)

In [52]:
sales_matrix.ndim

2

In [53]:
sales_matrix.size

12

In [55]:
profit = [433,212,433,212]
profit_array = np.array([profit])

In [57]:
profit_array.shape

(1, 4)

In [58]:
profit_array.ndim

2

In [59]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [60]:
sales_matrix[2,1]

np.int64(5645)

In [63]:
sales_matrix[1:,1:3]

array([[2322, 1222],
       [5645, 6564]])

In [64]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [65]:
profit_us = [544,655,233,544]
profit_eu = [233,322,322,121]
profit_in = [544,122,433,122]

In [66]:
profit_matrix = np.array([profit_us,profit_eu,profit_in])

In [67]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [68]:
profit_matrix

array([[544, 655, 233, 544],
       [233, 322, 322, 121],
       [544, 122, 433, 122]])

In [70]:
np.round(profit_matrix/sales_matrix,2)

array([[0.12, 0.53, 0.05, 0.44],
       [0.04, 0.14, 0.26, 0.03],
       [0.08, 0.02, 0.07, 0.04]])

In [72]:
np.mean(sales_matrix)

np.float64(3903.1666666666665)

In [88]:
np.mean(sales_matrix,axis=0)
#Axis = 1 - Row by Row 
#Axis = 0 - Col by Col

array([5506.66666667, 3066.66666667, 4073.        , 2966.33333333])

In [77]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [89]:
np.average(sales_matrix,axis=0)

array([5506.66666667, 3066.66666667, 4073.        , 2966.33333333])

In [93]:
sales_matrix[sales_matrix>5000]

array([5433, 6554, 5645, 6564])

In [94]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [96]:
sales_matrix[np.where(sales_matrix>5000)]

array([5433, 6554, 5645, 6564])

In [100]:
list(np.where(sales_matrix>5000))

[array([1, 2, 2, 2]), array([0, 0, 1, 2])]

In [99]:
np.where(sales_matrix>5000,"Good Sales",sales_matrix)

array([['4533', '1233', '4433', '1223'],
       ['Good Sales', '2322', '1222', '4332'],
       ['Good Sales', 'Good Sales', 'Good Sales', '3344']], dtype='<U21')

In [101]:
np.where((sales_matrix > 5000) & (sales_matrix < 6000), "Good Sales", sales_matrix)

array([['4533', '1233', '4433', '1223'],
       ['Good Sales', '2322', '1222', '4332'],
       ['6554', 'Good Sales', '6564', '3344']], dtype='<U21')

In [102]:
sales_matrix

array([[4533, 1233, 4433, 1223],
       [5433, 2322, 1222, 4332],
       [6554, 5645, 6564, 3344]])

In [107]:
array1= np.arange(1,21)

In [109]:
array1.shape

(20,)

In [125]:
np.reshape(array1,(10,-1),order="F")

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19],
       [10, 20]])

In [113]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, /, shape=None, order='C', *, newshape=None, copy=None)
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    shape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of ``a`` using this index order, and place the
        elements into the reshaped array using this index order. 'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        changing fastest, and the last index changing slowest. Note that
        the 'C' and 'F' options take no account of the memory layout of
        the underlying array, and only refer to the order of indexing.
        'A' means to read / write the elements in Fortran-like index
        order if ``a`` is Fortran *contiguous* in memory, C-like order
        otherwise.
    newshape : int or tuple of ints
        .. deprecated:: 2.1
            Replaced by ``shape`` argument. Retained for backward
            compatibility.
    copy : bool, optional
        If ``True``, then the array data is copied. If ``None``, a copy will
        only be made if it's required by ``order``. For ``False`` it raises
        a ``ValueError`` if a copy cannot be avoided. Default: ``None``.

    Returns
    -------
    reshaped_array : ndarray
        This will be a new view object if possible; otherwise, it will
        be a copy.  Note there is no guarantee of the *memory layout* (C- or
        Fortran- contiguous) of the returned array.

    See Also
    --------
    ndarray.reshape : Equivalent method.

    Notes
    -----
    It is not always possible to change the shape of an array without copying
    the data.

    The ``order`` keyword gives the index ordering both for *fetching*
    the values from ``a``, and then *placing* the values into the output
    array. For example, let's say you have an array:

    >>> a = np.arange(6).reshape((3, 2))
    >>> a
    array([[0, 1],
           [2, 3],
           [4, 5]])

    You can think of reshaping as first raveling the array (using the given
    index order), then inserting the elements from the raveled array into the
    new array using the same kind of index ordering as was used for the
    raveling.

    >>> np.reshape(a, (2, 3)) # C-like index ordering
    array([[0, 1, 2],
           [3, 4, 5]])
    >>> np.reshape(np.ravel(a), (2, 3)) # equivalent to C ravel then C reshape
    array([[0, 1, 2],
           [3, 4, 5]])
    >>> np.reshape(a, (2, 3), order='F') # Fortran-like index ordering
    array([[0, 4, 3],
           [2, 1, 5]])
    >>> np.reshape(np.ravel(a, order='F'), (2, 3), order='F')
    array([[0, 4, 3],
           [2, 1, 5]])

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1,2,3], [4,5,6]])
    >>> np.reshape(a, 6)
    array([1, 2, 3, 4, 5, 6])
    >>> np.reshape(a, 6, order='F')
    array([1, 4, 2, 5, 3, 6])

    >>> np.reshape(a, (3,-1))       # the unspecified value is inferred to be 2
    array([[1, 2],
           [3, 4],
           [5, 6]])

**https://pandas.pydata.org/**

In [126]:
#Installation 
!pip install pandas

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [131]:
import pandas as pd

In [132]:
pd.__version__

'2.2.3'

In [169]:
stu_details = {"s_id":[1,2,3,4,5], "sname":["A","B","C","D","E"], "sregion":["N","S","S","W","E"]}

In [143]:
stu_details

{'sid': [1, 2, 3, 4, 5],
 'sname': ['A', 'B', 'C', 'D', 'E'],
 'sregion': ['N', 'S', 'S', 'W', 'E']}

In [170]:
df1= pd.DataFrame(stu_details)

In [148]:
df2 = pd.DataFrame(np.array([[1,"Py",10],[2,"R",12],[3,"PBI",5],[4,"Py",10],[6,"R",12]]),columns=["sid","ssub","smarks"])

In [152]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sid      5 non-null      int64
 1   sname    5 non-null      object
 2   sregion  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [162]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sid     5 non-null      int64
 1   ssub    5 non-null      object
 2   smarks  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [171]:
df1

   s_id sname sregion
0     1     A       N
1     2     B       S
2     3     C       S
3     4     D       W
4     5     E       E

In [172]:
df2

   sid ssub  smarks
0    1   Py      10
1    2    R      12
2    3  PBI       5
3    4   Py      10
4    6    R      12

In [159]:
df2["sid"]=df2.sid.astype(int)

In [161]:
df2["smarks"]=df2.smarks.astype(int)

In [167]:
pd.merge(df1,df2,on="sid",how="outer")

   sid sname sregion ssub  smarks
0    1     A       N   Py    10.0
1    2     B       S    R    12.0
2    3     C       S  PBI     5.0
3    4     D       W   Py    10.0
4    5     E       E  NaN     NaN
5    6   NaN     NaN    R    12.0

In [174]:
pd.merge(df1,df2,left_on="s_id",right_on="sid",how="outer")

   s_id sname sregion  sid ssub  smarks
0   1.0     A       N  1.0   Py    10.0
1   2.0     B       S  2.0    R    12.0
2   3.0     C       S  3.0  PBI     5.0
3   4.0     D       W  4.0   Py    10.0
4   5.0     E       E  NaN  NaN     NaN
5   NaN   NaN     NaN  6.0    R    12.0

In [ ]:
pd.merge(df1,df2,on=["col1","col2"],how="inner")

In [ ]:
pd.merge(df1,df2,left_on=["col1","col2"], right_on=["col_1","col_2"],how="inner")

In [ ]:
pd.merge(df4,pd.merge(df3,pd.merge(df1,df2,on="col1",how="inner"),on="col2",how="left"),on="col3")

In [176]:
stu_details_us = {"s_id":[1,2,3,4,5], "sname":["A","B","C","D","E"], "sregion":["N_US","S_US","S_US","W_US","E_US"]}
stu_details_in = {"s_id":[6,7,8,9,5], "sname":["P","Q","R","S","E"], "sregion":["N_IN","S_IN","S_IN","W_IN","E_US"]}

In [180]:
df1= pd.DataFrame(stu_details_us)

In [181]:
df2 = pd.DataFrame(stu_details_in)

In [182]:
df1

   s_id sname sregion
0     1     A    N_US
1     2     B    S_US
2     3     C    S_US
3     4     D    W_US
4     5     E    E_US

In [183]:
df2

   s_id sname sregion
0     6     P    N_IN
1     7     Q    S_IN
2     8     R    S_IN
3     9     S    W_IN
4     5     E    E_US

In [188]:
pd.concat([df1,df2],axis=0).reset_index(drop="index")

   s_id sname sregion
0     1     A    N_US
1     2     B    S_US
2     3     C    S_US
3     4     D    W_US
4     5     E    E_US
5     6     P    N_IN
6     7     Q    S_IN
7     8     R    S_IN
8     9     S    W_IN
9     5     E    E_US

In [195]:
output = pd.concat([df1,df2],axis=0).reset_index().drop("index",axis=1)

In [198]:
output = output.drop_duplicates()

In [202]:
output.to_excel("mydta.xlsx",sheet_name="stu_details",index=False)

In [201]:
import os
os.getcwd()

'C:\\Users\\Dell\\Downloads'

In [203]:
pd.read_csv(r"D:\OneDrive - Rahul Tiwari\Desktop\tips.csv")

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [204]:
os.chdir(r"D:\OneDrive - Rahul Tiwari\Desktop")

In [205]:
os.getcwd()

'D:\\OneDrive - Rahul Tiwari\\Desktop'

In [207]:
tips = pd.read_csv("tips.csv")

In [209]:
type(tips)

pandas.core.frame.DataFrame

In [211]:
len(tips)

244

In [213]:
len(tips.columns)

7

In [215]:
tips.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [217]:
tips.tail(3)

     total_bill   tip     sex smoker   day    time  size
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [218]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [221]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [225]:
tips.rename(columns={"sex":"gender", "size":"noofcust"},inplace=True)

In [227]:
tips[["total_bill","gender","noofcust"]]

     total_bill  gender  noofcust
0         16.99  Female         2
1         10.34    Male         3
2         21.01    Male         3
3         23.68    Male         2
4         24.59  Female         4
..          ...     ...       ...
239       29.03    Male         3
240       27.18  Female         2
241       22.67    Male         2
242       17.82    Male         2
243       18.78  Female         2

[244 rows x 3 columns]

In [231]:
type(tips[["tip"]])

pandas.core.frame.DataFrame

In [233]:
type(tips["tip"])

pandas.core.series.Series

In [235]:
tips[["tip","day"]]

      tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [242]:
tips.iloc[0:3,0:3]

   total_bill   tip  gender
0       16.99  1.01  Female
1       10.34  1.66    Male
2       21.01  3.50    Male

In [245]:
tips

     total_bill   tip  gender smoker   day    time  noofcust
0         16.99  1.01  Female     No   Sun  Dinner         2
1         10.34  1.66    Male     No   Sun  Dinner         3
2         21.01  3.50    Male     No   Sun  Dinner         3
3         23.68  3.31    Male     No   Sun  Dinner         2
4         24.59  3.61  Female     No   Sun  Dinner         4
..          ...   ...     ...    ...   ...     ...       ...
239       29.03  5.92    Male     No   Sat  Dinner         3
240       27.18  2.00  Female    Yes   Sat  Dinner         2
241       22.67  2.00    Male    Yes   Sat  Dinner         2
242       17.82  1.75    Male     No   Sat  Dinner         2
243       18.78  3.00  Female     No  Thur  Dinner         2

[244 rows x 7 columns]

In [247]:
tips.iloc[:,0:7:3]

     total_bill smoker  noofcust
0         16.99     No         2
1         10.34     No         3
2         21.01     No         3
3         23.68     No         2
4         24.59     No         4
..          ...    ...       ...
239       29.03     No         3
240       27.18    Yes         2
241       22.67    Yes         2
242       17.82     No         2
243       18.78     No         2

[244 rows x 3 columns]

In [249]:
tips.head(1)

   total_bill   tip  gender smoker  day    time  noofcust
0       16.99  1.01  Female     No  Sun  Dinner         2

In [254]:
tips.iloc[[0,10,20,30],[0,1,4,6]].values

array([[16.99, 1.01, 'Sun', 2],
       [10.27, 1.71, 'Sun', 2],
       [17.92, 4.08, 'Sat', 2],
       [9.55, 1.45, 'Sat', 2]], dtype=object)

In [253]:
tips.iloc[:,:]

     total_bill   tip  gender smoker   day    time  noofcust
0         16.99  1.01  Female     No   Sun  Dinner         2
1         10.34  1.66    Male     No   Sun  Dinner         3
2         21.01  3.50    Male     No   Sun  Dinner         3
3         23.68  3.31    Male     No   Sun  Dinner         2
4         24.59  3.61  Female     No   Sun  Dinner         4
..          ...   ...     ...    ...   ...     ...       ...
239       29.03  5.92    Male     No   Sat  Dinner         3
240       27.18  2.00  Female    Yes   Sat  Dinner         2
241       22.67  2.00    Male    Yes   Sat  Dinner         2
242       17.82  1.75    Male     No   Sat  Dinner         2
243       18.78  3.00  Female     No  Thur  Dinner         2

[244 rows x 7 columns]

In [258]:
tips[(tips["gender"]=="Female") & (tips["total_bill"]>40)]

     total_bill  tip  gender smoker   day    time  noofcust
102       44.30  2.5  Female    Yes   Sat  Dinner         3
197       43.11  5.0  Female    Yes  Thur   Lunch         4

In [259]:
tips[(tips["gender"]=="Female") | (tips["total_bill"]>40)]

     total_bill   tip  gender smoker   day    time  noofcust
0         16.99  1.01  Female     No   Sun  Dinner         2
4         24.59  3.61  Female     No   Sun  Dinner         4
11        35.26  5.00  Female     No   Sun  Dinner         4
14        14.83  3.02  Female     No   Sun  Dinner         2
16        10.33  1.67  Female     No   Sun  Dinner         3
..          ...   ...     ...    ...   ...     ...       ...
226       10.09  2.00  Female    Yes   Fri   Lunch         2
229       22.12  2.88  Female    Yes   Sat  Dinner         2
238       35.83  4.67  Female     No   Sat  Dinner         3
240       27.18  2.00  Female    Yes   Sat  Dinner         2
243       18.78  3.00  Female     No  Thur  Dinner         2

[95 rows x 7 columns]

In [261]:
tips.day.unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [268]:
tips[~tips["day"].isin({"Sun","Sat","Fri"})]

     total_bill   tip  gender smoker   day    time  noofcust
77        27.20  4.00    Male     No  Thur   Lunch         4
78        22.76  3.00    Male     No  Thur   Lunch         2
79        17.29  2.71    Male     No  Thur   Lunch         2
80        19.44  3.00    Male    Yes  Thur   Lunch         2
81        16.66  3.40    Male     No  Thur   Lunch         2
..          ...   ...     ...    ...   ...     ...       ...
202       13.00  2.00  Female    Yes  Thur   Lunch         2
203       16.40  2.50  Female    Yes  Thur   Lunch         2
204       20.53  4.00    Male    Yes  Thur   Lunch         4
205       16.47  3.23  Female    Yes  Thur   Lunch         3
243       18.78  3.00  Female     No  Thur  Dinner         2

[62 rows x 7 columns]

In [270]:
tips.groupby(["smoker","gender"]).size()

smoker  gender
No      Female    54
        Male      97
Yes     Female    33
        Male      60
dtype: int64

In [275]:
tips.groupby(["day","gender"]).agg({"total_bill":np.mean, "tip":np.mean}).to_excel("mydata.xlsx")

C:\Users\Dell\AppData\Local\Temp\ipykernel_36212\1145843926.py:1: FutureWarning: The provided callable <function mean at 0x000001E115298400> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  tips.groupby(["day","gender"]).agg({"total_bill":np.mean, "tip":np.mean}).to_excel("mydata.xlsx")
C:\Users\Dell\AppData\Local\Temp\ipykernel_36212\1145843926.py:1: FutureWarning: The provided callable <function mean at 0x000001E115298400> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  tips.groupby(["day","gender"]).agg({"total_bill":np.mean, "tip":np.mean}).to_excel("mydata.xlsx")

In [280]:
pd.pivot_table(data=tips,columns=["time"],index=["smoker","gender"],values="total_bill",aggfunc="sum")

time            Dinner   Lunch
smoker gender
No     Female   580.12  397.56
       Male    1550.02  369.73
Yes    Female   418.96  174.31
       Male    1111.20  225.87

In [282]:
tips["tot_rev"] = (tips.total_bill*tips.noofcust)+tips.tip

In [286]:
tips.sort_values("tot_rev",ascending=False)

     total_bill   tip  gender smoker   day    time  noofcust  tot_rev
156       48.17  5.00    Male     No   Sun  Dinner         6   294.02
141       34.30  6.70    Male     No  Thur   Lunch         6   212.50
142       41.19  5.00    Male     No  Thur   Lunch         5   210.95
212       48.33  9.00    Male     No   Sat  Dinner         4   202.32
59        48.27  6.73    Male     No   Sat  Dinner         4   199.81
..          ...   ...     ...    ...   ...     ...       ...      ...
92         5.75  1.00  Female    Yes   Fri  Dinner         2    12.50
82        10.07  1.83  Female     No  Thur   Lunch         1    11.90
222        8.58  1.92    Male    Yes   Fri   Lunch         1    10.50
111        7.25  1.00  Female     No   Sat  Dinner         1     8.25
67         3.07  1.00  Female    Yes   Sat  Dinner         1     4.07

[244 rows x 8 columns]

In [287]:
#0-50 - Bronze
#51-100 - Silver
#101-150 - Gold 
#151-200 - Platinum
#201 - Diamond

In [288]:
def cust_seg(tot_rev):
    if tot_rev<=50:
        return "Bronze Customer"
    elif tot_rev>50 and tot_rev<=100:
        return "Silver Customer"
    elif tot_rev>100 and tot_rev<=150:
        return "Gold Customer"
    elif tot_rev>150 and tot_rev<=200:
        return "Platinum Customer"
    else:
        return "Diamond Customer"

In [290]:
tips["cs"] = tips.tot_rev.apply(cust_seg)

In [294]:
tips.groupby("cs").count()

,total_bill,tip,gender,smoker,day,time,noofcust,tot_rev
cs,,,,,,,,
Bronze Customer,143,143,143,143,143,143,143,143
Diamond Customer,4,4,4,4,4,4,4,4
Gold Customer,23,23,23,23,23,23,23,23
Platinum Customer,11,11,11,11,11,11,11,11
Silver Customer,63,63,63,63,63,63,63,63

In [295]:
tips

,total_bill,tip,gender,smoker,day,time,noofcust,tot_rev,cs
0,16.99,1.01,Female,No,Sun,Dinner,2,34.99,Bronze Customer
1,10.34,1.66,Male,No,Sun,Dinner,3,32.68,Bronze Customer
2,21.01,3.50,Male,No,Sun,Dinner,3,66.53,Silver Customer
3,23.68,3.31,Male,No,Sun,Dinner,2,50.67,Silver Customer
4,24.59,3.61,Female,No,Sun,Dinner,4,101.97,Gold Customer
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,93.01,Silver Customer
240,27.18,2.00,Female,Yes,Sat,Dinner,2,56.36,Silver Customer
241,22.67,2.00,Male,Yes,Sat,Dinner,2,47.34,Bronze Customer
242,17.82,1.75,Male,No,Sat,Dinner,2,37.39,Bronze Customer
243,18.78,3.00,Female,No,Thur,Dinner,2,40.56,Bronze Customer

In [296]:
def calc_rev(row):
    if row.gender == "Male":
        return (row.total_bill * row.noofcust) + row.tip
    else:
        return row.total_bill * row.noofcust

tips["tot_rev_new"] = tips.apply(calc_rev, axis=1)

#tips["cs"] = tips.tot_rev.apply(cust_seg)

In [297]:
tips

,total_bill,tip,gender,smoker,day,time,noofcust,tot_rev,cs,tot_rev_new
0,16.99,1.01,Female,No,Sun,Dinner,2,34.99,Bronze Customer,33.98
1,10.34,1.66,Male,No,Sun,Dinner,3,32.68,Bronze Customer,32.68
2,21.01,3.50,Male,No,Sun,Dinner,3,66.53,Silver Customer,66.53
3,23.68,3.31,Male,No,Sun,Dinner,2,50.67,Silver Customer,50.67
4,24.59,3.61,Female,No,Sun,Dinner,4,101.97,Gold Customer,98.36
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,93.01,Silver Customer,93.01
240,27.18,2.00,Female,Yes,Sat,Dinner,2,56.36,Silver Customer,54.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,47.34,Bronze Customer,47.34
242,17.82,1.75,Male,No,Sat,Dinner,2,37.39,Bronze Customer,37.39
243,18.78,3.00,Female,No,Thur,Dinner,2,40.56,Bronze Customer,37.56

# End